.TH LISTLOGINS "1" "January 2010" "Toolserver" "User Commands"
.SH NAME
listlogins \- list other login sessions for the current user
.SH SYNOPSIS
.B listlogins
.SH DESCRIPTION
.PP
.B listlogins
lists all other login sessions, if any, for the current user,
printing the IP address and tty of the login.  If no other logins
exist, nothing is printed.
.SH SEE ALSO
\fBlistlogins\fR(1)
.SH AUTHOR
.B listlogins
was written by River Tarnell <river.tarnell@wikimedia.de>.
