.TH ACCTEXP "1" "January 2010" "Toolserver" "User Commands"
.SH NAME
acctexp \- print account expiry date
.SH SYNOPSIS
.B acctexp
[\fUusername\fR]
.SH DESCRIPTION
.PP
.B acctexp
prints the current expiry date of your account, or the account specified
by the \fUusername\fR option.  If the account has no expiry date, nothing
is printed.
.PP
Only the super-user may view the expiry date of another account.
.SH AUTHOR
.B acctexp
was written by River Tarnell <river.tarnell@wikimedia.de>.
