#! /bin/ksh
# Invoke /usr/bin/passwd with an explicit username parameter.  This works around
# an issue where passwd doesn't work for login names > 8 characters.

/usr/bin/passwd $(getent passwd $(/opt/ts/gnu/bin/id -u) | nawk -F: '{print $1}')
