.TH DAYS2DATE "1" "January 2010" "Toolserver" "User Commands"
.SH NAME
days2date \- convert days since 1970 into days
.SH SYNOPSIS
.B days2date
\fUdays\fR
.SH DESCRIPTION
.PP
.B days2date
prints the date at \fUdays\fR days since January 1st, 1970, with \fB0\fR
being 1970-01-01.
.SH SEE ALSO
\fBdate2days\fR(1)
.SH AUTHOR
.B days2date
was written by River Tarnell <river.tarnell@wikimedia.de>.
