.TH SETMAIL "1" "January 2010" "Toolserver" "User Commands"
.SH NAME
setmail \- set or change Toolserver email address
.SH SYNOPSIS
.B setmail
.SH DESCRIPTION
.PP
.B setmail
is used to set or change your Toolserver email address.  If you currently
have an email address set, 
.B setmail
will print the current address and ask if you wish to change it.  
.PP
Before using \fBsetmail\fR, you need to set your LDAP password with
\fBsetpass\fR(1).
.SH SEE ALSO
\fBsetpass\fR(1)
.SH AUTHOR
.B setmail
was written by River Tarnell <river.tarnell@wikimedia.de>.
