.TH SETLICENSE "1" "MAY 2010" "Toolserver" "User Commands"
.SH NAME
setlicense \- set or change Toolserver default license
.SH SYNOPSIS
.B setlicense
.SH DESCRIPTION
.PP
\fBsetlicense\fR is used to set or change your Toolserver default license.  If
you currently have a default license set, \fBsetlicense\fR will print the
current license and ask if you wish to change it.
.PP
Before using \fBsetlicense\fR, you need to set your LDAP password with
\fBsetpass\fR(1).
.SH SEE ALSO
\fBsetpass\fR(1)
.SH AUTHOR
\fBsetlicense\fR was written by River Tarnell <river.tarnell@wikimedia.de>.
