.TH DATE2DAYS "1" "January 2010" "Toolserver" "User Commands"
.SH NAME
date2days \- convert date into days since 1970
.SH SYNOPSIS
.B date2days
\fUdate\fR
.SH DESCRIPTION
.PP
.B date2days
takes a date in the form "\fUYYYY\fR-\fUMM\fR-\fUDD\fR", and prints the
number of days from January 1st, 1970 until the given date, with 1970-01-01
being 0 days.
.SH SEE ALSO
\fBdays2date\fR(1)
.SH AUTHOR
.B date2days
was written by River Tarnell <river.tarnell@wikimedia.de>.
