.TH ACCTRENEW "1" "May 2010" "Toolserver" "User Commands"
.SH NAME
acctrenew \- renew your account
.SH SYNOPSIS
.B acctrenew
.SH DESCRIPTION
.PP
\fBacctrenew\fR is used to extend the expiry date of your account.  It
should be run when your account is close to expiry, and will reset the
expiry date to six months from the current date.  Before your account is
renewed, you will be asked to confirm your email address and default
license.
.SH AUTHOR
\fBacctrenew\fR was written by River Tarnell <river.tarnell@wikimedia.de>.
.SH SEE ALSO
.LP
\fBacctexp\fR(1)
